FROM docker.io/ubuntu:24.04 as ubuntu-base

FROM ubuntu-base as base-packages

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils \
    build-essential \
    ca-certificates \
    g++ \
    cmake \
    curl \
    git \
    libc-dev \
    liblapack-dev \
    libopenblas64-serial-dev \
    libopenmpi-dev \
    libtool \
    locales \
    ninja-build \
    time \
    tzdata \
    wget \
    pkg-config \
    libgmp-dev \
    libsuitesparse-dev \
    gfortran \
    dos2unix \
    vim \
    tmux \
    libx11-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev

# Currently (2025-12-02) unsuitable without hacks:
# coinor-libipopt-dev
# coinor-libbonmin-dev \

RUN mkdir -p /usr/src/coin-or && \
    mkdir -p /opt/coin-or && \
    cd /usr/src/coin-or && \
    wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew \
    && chmod +x coinbrew

RUN cd /usr/src/coin-or && ./coinbrew fetch https://github.com/coin-or-tools/ThirdParty-Mumps@3.0.11

RUN cd /usr/src/coin-or && ./coinbrew fetch Ipopt@3.14.19 --skip-update
RUN cd /usr/src/coin-or && ./coinbrew fetch Bonmin@master --skip-update

RUN cd /usr/src/coin-or && ./coinbrew build Ipopt@3.14.19 --verbosity 2 --skip-update --prefix=/opt/coin-or --parallel-jobs 8 --tests none
RUN cd /usr/src/coin-or && ./coinbrew build Bonmin@master --verbosity 2 --skip-update --prefix=/opt/coin-or --parallel-jobs 8 --tests none

RUN ln -s /opt/coin-or/include/coin-or /opt/coin-or/include/coin

# build ovm.io
RUN git clone --recurse-submodules https://github.com/LIHPC-Computational-Geometry/ovm.io.git /usr/src/ovm.io

RUN cmake -S /usr/src/ovm.io -B /usr/src/ovm.io/build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS="-Wno-error=implicit-int" \
        -G Ninja && \
    ninja -C /usr/src/ovm.io/build && \
    cp /usr/src/ovm.io/build/ovm.io /usr/local/bin/ovm.io